[theme]

# Primary accent for interactive elements
primaryColor = '#5d4037'

# Background color for the main content area
backgroundColor = '#FEF8EF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#5d4037'

# Color used for almost all text
textColor = '#5d4037'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"